urls.py
from django.conf.urls import url
from . import views

app_name = 'wordclouds'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cloud/$', views.cloud, name='cloud'),
    url(r'^cloud_training/?$', views.cloud_training, name='cloud_training'),
    url(r'^username/$', views.username, name='username'),
    url(r'^send_username/?$', views.send_username, name='send_username'),
    url(r'^user_feedback/?$', views.user_feedback, name='user_feedback'),
    url(r'^problem/(?P<problem_id>\d+)?$', views.fetch_problem, name='problem'),
    url(r'^submit/?$', views.submit, name='submit'),
    url(r'^completed_cloud/?$', views.completed_cloud, name='completed_cloud'),
    url(r'^synonyms/(?P<word>[\w\d._-]+)?$', views.fetch_synonyms, name='synonyms'),
    url(r'^word/(?P<word>[\w\d._-]+)?$', views.fetch_word, name='word'),
    url(r'^word_senses/(?P<word>[\w\d._-]+)?$', views.fetch_word_senses, name='word_senses'),
    url(r'^results/?$', views.results, name='results'),
    url(r'^similarity_query/(?P<method>[\w\d._-]+)?$', views.similarity_query, name='similarity_query'),
]

templates/wordclouds/cloud.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Cloud App</title>

	{% load staticfiles %}
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'wordclouds/styles/cloud_style.css' %}">

	<script>
		var problem_id = {{ problem_id }};
	 	var url_submit = "{% url 'wordclouds:submit' %}";
	 	var url_completed = "{% url 'wordclouds:completed_cloud' %}";
		var url_problem = "{% url 'wordclouds:problem' %}" + problem_id;
		var problem_data = {{ problem_data|safe }};
	</script>

</head>
<body>
	<div data-role="header">
		<div id="top-bar">
			<div style="width:100%" class="clear">
				<h1 id="title">Word Cloud Game</h1> 
				<div id="score_box">Score: <div id="score" style="float:right">0</div></div>
			</div>
			
			<div data-inset="false" data-collapsed="false" id="instructions" title="Instructions" style="width:80%; margin-left: 5%">
				<h4>Instructions (Click to Collapse)</h4>
				<br> It's time to play! Your goal is to <b>find as many synonyms as possible</b> for each of the word in the sentence. Your score is the total number of words you've added to the cloud. Aim for a score of 8 synonyms for each word.  
				<div style="padding-left: 4%">
					<br> (1) Click on a word to load suggested synonyms in the word bank.
					<br> (2) Add words by typing them in
					<br> (3) Drag in suggested synonyms from the Word Bank
					<br> (4) Repeat for all words that are not "grayed out"
				</div>
				<br>
				Tips:
				<div style="padding-left: 4%">
					<br> - Add synonyms for all words in the sentence, except any words that are 'greyed out' (it won't let you add any).
					<br> - Only add synonyms that fit the meaning of the word in the sentence. If the sentence says "I had a blast at the party", then "explosion" is not a good synonym for "blast". "Fun" is a better synonym.
					<br> - Remember to think about whether a word goes in the generic or specific bin
					<br> - You don't have to use all the words in the word bank
					<br> - If you need additional context to understand the sentence, the abstract from which this problem was taken is at the bottom of the page. 
				</div>
				<br>Click 'submit' when you have finished.
				<br>
			</div>
		</div>
	</div>
	<div data-role="main" class="ui-content" id="cloud-area">

		<div class="clear"><a>Sentence: </a><h2 id="sentence_text" style="display:inline"></h2><a id="to_abstract"> (more info)</a></div>
		<div id="left-menu" data-role="collapsible" data-collapsed="false" class="quarter">
			<h4>Word Bank</h4>
		</div>
		<div id="sentence_container" class="clear">
			<ul id="sentence" class="ui-listview" data-role="listview">
			</ul>
		</div>
		<div data-role="collapsible" id="abstract" title="Full abstract from original problem">	
				<h4>Full abstract from original problem (Click to Expand)</h4>
				<div id="abstract_text">
					{{ abstract }}
				</div>
		</div>
	</div>

	<div data-role="footer" id="foot">
		<h1> Thanks for completing the task. When you are finished, click submit </h1>
		<input type="button" value="submit" id="submit" class="ui-btn" onclick="submitCloud()">
	</div>

<!--TEMPLATES -->
<div id="word_item_template" style="display:none">
	<li class="word_item ui-li-has-alt" sense="new.n.1">
		<a href="#" class="ui-btn word_text">new</a>
		<a class="ui-btn ui-icon-delete ui-btn-icon-left ui-btn-icon-notext ui-icon-carat-r" title=""></a>
	</li>
</div>
<div id="add_button_template" style="display:none">
	<li class="add_button ui-li-has-alt">
		<a href="#" class="ui-btn">
			<input type="text" class="add-word-input" placeholder="Type Word Here">
		</a>
		<a class="ui-btn ui-icon-plus ui-btn-icon-left new-word"></a>
	</li>
</div>
<div id="word_sense_template" style="display:none">
	<div class="sense_div" data-role="collapsible2" data-collapsed="false" >
	    <h4>Sense (Type)</h4>
	    <ul data-role="listview" class="sort word1">
	    </ul>
    </div>
</div>
<div id="word_sentence_template" style="display:none">
	<li class="word_column ui-li-has-alt">
		<div id="word_sentence_" class="quarter word_column_div" data-collapsed="true" >
		    <h4 class="word_name">Word</h4>
		    <div class="collapsible3">
			    <h4 class="concrete_label">Specific</h4>
			    <ul data-role="listview" class="sort word1 concrete" abstraction="concrete">
			    </ul>
		    </div>
		    <div class="collapsible3">
		    	<h4 class="abstract_label">General</h4>
			    <ul data-role="listview" class="sort word1 abstract" abstraction="abstract">
			    </ul>
		    </div>
	    </div>

    </li>
</div>

<form name="cloud_form" id="cloud_form" method="POST" action="{% url 'wordclouds:submit' %}">
	<input type="hidden" id="cloud_data" name="cloud_data" value="" />
</form>

<script src="{% static 'wordclouds/scripts/cloud.js' %}"></script>

</body>
</html>

templates/wordclouds/cloud_training.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Cloud App Training</title>

	{% load staticfiles %}
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'wordclouds/styles/cloud_style.css' %}">

	<script> var cloud_url = "{% url 'wordclouds:cloud' %}"; </script>
</head>
<body>
	<div data-role="header">
		<div id="top-bar">
			<div style="width:100%" class="clear">
				<h1 id="title">Word Cloud Game <span style="color:#333">Training</span></h1> 
			</div>
			<div data-inset="false" data-collapsed="false" id="instructions" style="width:80%; margin-left: 5%">
				<h4>Instructions (Click to Collapse)</h4>
				<br> The goal of this task is to <b>find synonyms and related words for each word in a sentence</b>. We are going to practice with "cook".
					<div style="padding-left: 4%">
						<br> (1) Add a couple synonyms for "cook" by typing them in
						<br> (2) Drag words from the Word Bank into the appropriate bins under "cook"
						<br> (3) Click Next when you are done
					</div>
				<br><br> Notice that each word has two bins, 'specific' and 'general'. Put domain-specific words into the specific bin, and more generic or abstract words into the 'general' bin. For example, 'Golden Retriever' is a specific synonym of dog, while 'animal' is a general synonym of dog.
				<br><br> We've already done 'dog' and 'run' as examples. Complete the 'cook' column, then click "Next" at the bottom of the page.
				<br><br>
				<input type="button" value="Start" id="start" class="ui-btn">
			</div>
		</div>
	</div>
<!-- 	<div id="instructions">
			<br> The goal of this task is to find synonyms and related words for each word in a sentence. We are going to practice with "cook".
				<div style="padding-left: 30px">
					<br> (1) Add a couple synonyms for "cook" by typing them in
					<br> (2) Drag words from the Word Bank into the appropriate bins under "cook"
					<br> (4) Click Next when you are done
				</div>
			<p> Notice that each word has two bins, 'specific' and 'general'. Put domain-specific words into the specific bin, and more generic or abstract words into the 'general' bin. For example, 'Golden Retriever' is a specific synonym of dog, while 'animal' is a general synonym of dog.
			<p> We've already done 'dog' and 'run' as examples. Complete the 'cook' column, then click "Next" at the bottom of the page.
		</div>
	</div> -->
	<div data-role="main" class="ui-content" id="cloud-area">

		<h2>Try completing this mini-cloud by dragging synonyms from the Word Bank into the "Cook" bin.</h2>
		<div id="left-menu" data-role="collapsible" data-collapsed="false" class="quarter">
			<h4>Word Bank: "Cook"</h4>
		</div>
		<div id="sentence_container" class="clear">
			<ul id="sentence" class="ui-listview" data-role="listview">
			</ul>
		</div>
	</div>
	<div data-role="footer" id="foot" style="padding:2%">
		<h1> If you are ready to continue, click 'next' </h1>
		<input type="button" value="next" id="next" class="ui-btn" onclick="next()">
	</div>

<!--TEMPLATES -->
<div id="word_item_template" style="display:none">
	<li class="word_item ui-li-has-alt" sense="new.n.1">
		<a href="#" class="ui-btn word_text">new</a>
		<a class="ui-btn ui-icon-plus ui-btn-icon-left ui-btn-icon-notext ui-icon-carat-r" title=""></a>
	</li>
</div>
<div id="word_item_template_ex" style="display:none">
	<li class="word_item ui-li-has-alt" sense="new.n.1">
		<a href="#" class="ui-btn word_text">new</a>
		<a class="ui-btn ui-icon-minus ui-btn-icon-left ui-btn-icon-notext ui-icon-carat-r" title=""></a>
	</li>
</div>

<div id="add_button_template" style="display:none">
	<li class="add_button ui-li-has-alt">
		<a href="#" class="ui-btn">
			<input type="text" class="add-word-input" placeholder="Type Word Here">
		</a>
		<a class="ui-btn ui-icon-plus ui-btn-icon-left new-word"></a>
	</li>
</div>
<div id="word_sense_template" style="display:none">
	<div class="sense_div" data-role="collapsible2" data-collapsed="false" >
	    <h4>"Cook" Word Bank</h4>
	    <ul data-role="listview" class="sort word1">
	    </ul>
    </div>
</div>
<div id="word_sentence_template" style="display:none">
	<li class="word_column ui-li-has-alt">
		<div id="word_sentence_" class="quarter word_column_div" data-collapsed="false" >
		    <h4 class="word_name">Word</h4>
		    <div class="collapsible3">
			    <h4 class="concrete_label">Specific</h4>
			    <ul data-role="listview" class="sort word1 concrete" abstraction="concrete">
			    </ul>
		    </div>
		    <div class="collapsible3">
		    	<h4 class="abstract_label">General</h4>
			    <ul data-role="listview" class="sort word1 abstract" abstraction="abstract">
			    </ul>
		    </div>
	    </div>

    </li>
</div>

<script src="{% static 'wordclouds/scripts/cloud_training.js' %}"></script>

</body>
</html>

templates/wordclouds/completed_cloud.html
<!doctype html>
<html lang="en" style="height:100%">
<head>
	<meta charset="utf-8">
	<title>Cloud App Completed</title>

	{% load staticfiles %}
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'wordclouds/styles/cloud_style.css' %}">

	<script>
		var feedback_url = "{% url 'wordclouds:user_feedback' %}";
	</script>

</head>
<body style="background-color:rgb(0, 136, 187); height:100%; width:100%">
	<div id="input_centered" class="center">
		<div id="completed" width="100%">
			Thank you for completing the word cloud task. Copy and paste this code into the Mechanical Turk HIT to get paid:
			<br>
			<span style="font-weight:bold; font-size:25px;" id="hash_code">{{completion_code}}</span>
		</div>
		<div style="padding:5%">
			<form method="POST" action="" id="feedback_form">
				{% csrf_token %}
				<input type="hidden" id="username" name="username" value="{{username}}" />
				<input type="hidden" id="trial" name="trial" value="{{trial}}" />
				<input type="hidden" id="problem_id" name="problem_id" value="{{problem_id}}" />
				Let us know how we can improve this HIT (optional):
				<textarea rows="4" style="width:100%; border-radius: 5px; border: none;" name="feedback_text" id="feedback_text" placeholder="type feedback here, then click on Send Feedback"></textarea>
				<input type="submit" id="submit" value="Send Feedback" class="button" style="margin:8px 20px">
			</form>
		</div>
	</div>

	<script>
		$(document).ready(function(){
		    var $form = $('#feedback_form');
		    $form.submit(function(){
		    	console.log("form submit");
				console.log($(this).serialize())
		    	$.post(feedback_url, $(this).serialize(), function(response){
					ft_elem = document.getElementById("feedback_text");
		    		ft_elem.placeholder='Thank you for your feedback!';
		    		ft_elem.value='';
					ft_elem.setAttribute('disabled', 'disabled');
					$("#submit").hide();
		        },'text');
		        return false;
			});
		});
	</script>

	<script src="{% static 'wordclouds/scripts/completed_cloud.js' %}"></script>

</body>
</html>

templates/wordclouds/results.html
<!doctype html>
<html lang="en" style="height:100%">
<head>
	<meta charset="utf-8">
	<title>Thunderclouds</title>

	{% load staticfiles %}
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'wordclouds/styles/cloud_style.css' %}">

	<!-- <script src="{% static 'wordclouds/scripts/data1.js' %}"></script> -->
	<script src="{% static 'wordclouds/scripts/data3.js' %}"></script>

	<script> 
		var url_tfidf = "{% url 'wordclouds:similarity_query' %}tfidf";
		var url_lsi = "{% url 'wordclouds:similarity_query' %}lsi";
	</script>

</head>
<body style="background-color:rgb(0, 136, 187); padding:15px;">

	<h1 style="color:#eee; font-weight:200; font-size:40px">Making it Rain: where the clouds collide</h1>
	<select id="dropdown"  onchange = "changeProblem(this)" style="max-width:90vw;">
		<option>Select a problem</option>
	</select>

	<h4>Problem Statement:</h4>
	<div id=problem style="color:#eee; font-size:1.7em;">Select a problem</div>

	<button class="button collapse_btn" id="toggle_abstract" style="margin:2px">Toggle Abstract</button><br>
	<div id="my_abstract" style="color:#eee; max-width:80vw; display:none">Select a problem</div>

	<img id="lightning" src="http://i488.photobucket.com/albums/rr250/KimiVengenz/Textures/Lightning-psd7258.png" style="position:fixed; width:100vw; top:0; display:none">

	<button class="rain_btn" id="toggle_options">Toggle Customization Pane</button>
	<div id="options" style="display:none;	background-color:#054e88; border-radius: 10px 10px 10px 10px; color:white; padding:10px">
		Scoring function: 
		<select id="scoring_function" onchange = "changeScoringFunction(this)">
			<option value="dumbo">Dumb matching</option>
			<option value="tfidf">tf-idf</option>
			<option value="lsi">LSI</option>
		</select>
		Scoring weights: <br>
		Entropy: When on, problems with overlap on many words are prefered to problems with overlap on one word
		<div class="slider" id="entropy_slider"></div>
		Parallel word scoring: Boost the score of problems with two matching words in a row, eg "bake cake" and "cook food"
		<div class="slider" id="parallel_slider"></div>

		<div id="lsi_dimensions_input" style="display:none;"> Number of LSI Dimensions: <input type="text" id="lis_dimensions" class="nice_input" style="width:40px" onkeyup="changeLsiDimensions(this)" placeholder="100"></div>

		<div id="customize">
			<ol id="sentence_list">
			</ol>
		</div>
		<div style="left:20vw;"><h4>Forbidden words in problem extraction (use, commas, like, this)</h4>
			<div id="forbidden_words" class="nice_input" contenteditable="true"></div>
		</div>
		<button class="rain_btn center" value="go" id="update_related_papers_button">Perform Rain Dance</button>
	</div>

	<div>
		<div style="float:left; margin-right:2vw"><h2> Thunder rolls and lightning strikes.... </h2></div>
		<div ><button id="save_query" class="rain_btn" onclick="saveQuery()">Save Query</button></div>
	</div>

	<div id="related_papers" style="border: solid 4px black; border-radius:5px; width: 90vw; margin:10px; max-height:80vh; overflow:auto" class="center"> 
	 	Select a problem to see related papers
	</div>

	<br>

	<button class="button" id="favorite_papers_btn" style="margin:2px">Favorite Papers (toggle)</button><br>
	<div id="favorite_papers_div" style="background-color:#eee; border-radius:5px; padding:10px; max-width:95vw; display:none"></div>

	<button class="button" id="problems_by_top_score_btn" style="margin:2px">List problems by top score (toggle)</button><br>
	<div id="problems_by_top_score" style="background-color:#eee; border-radius:5px; padding:10px; max-width:95vw; display:none"></div>

	<!-- Templates -->
	<div id="paper_template" style="display:none">
		<div class="paper" style="background:white; color:#28E; margin: 10px; padding:10px; border-radius:5px">
				<h3 style="margin:2px 0; display:inline;">Paper Extraction</h3> 
				<button class="star_button" onclick="starClicked(this)">
					<div style="" class="star_empty">&#9734;</div>
					<div style="display:none; position:absolute" class="star_filled">&#9733;</div>
				</button>
				<div class="score" style="color:#F39"></div>
				Overlapping synonyms: <div class="synonyms" style="color:#283">Synonym, and, or, others</div>
				<button class="button more_info_btn" style="margin:2px">toggle more info</button>
				<div class="more_info" style="display:none">
					ID: <div class="paper_id" style="color:black"></div>
					Abstract: <div class="abstract" style="color:black"></div>
				</div>
		</div>
	</div>
	<div id="word_table_template" style="display:none">
		<li class="clear" style="list-style: none;" word=""> 
			<div style="float:left; width:100px" class="t_word"> Sample 1 </div>
			<div style="float:left; margin-right:10px">
				Nouns <br>
				<input type="checkbox" class="check na_check" checked="true">Abstract<br>
				<input type="checkbox" class="check nc_check" checked="true">Concrete 
			</div>
			<div style="float:left">
				Verbs/other <br>
				<input type="checkbox" class="check va_check" checked="true">Abstract<br>
				<input type="checkbox" class="check vc_check" checked="true">Concrete 
			</div>
			<div style="float:left; margin:0 15px 15px 15px; padding:5px; border-radius: 5px; color:black; background-color:#eee; width:50vw" class="edit" contenteditable="true"></div>
			<br style="clear: both"><br>
		</li>
	</div>

	<script src="{% static 'wordclouds/scripts/results.js' %}"></script>

</body>
</html>

templates/wordclouds/username.html
<!doctype html>
<html lang="en" style="height:100%">
<head>
	<meta charset="utf-8">
	<title>Cloud App Login</title>

	{% load staticfiles %}
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'wordclouds/styles/cloud_style.css' %}">

	<script>
		var url = "{% url 'wordclouds:send_username' %}";
	</script>

</head>
<body style="background-color:rgb(0, 136, 187); height:100%; width:100%">
	<div id="input_centered" class="center">
		<div id="instructions" width="100%">
			Welcome to the word cloud interface.
			<br>
			Please enter your Mechanical Turk username:
			<form method="POST" action="" onsubmit="return go()" id="my_form">
				{% csrf_token %}
				<input type="text" name = "username" id="username" placeholder="username" class="text_input clear">
				<input type="submit" id="submit" value="Next" class="button" style="margin:8px">
			</form>
		</div>
	</div>

	<script>
		$(document).ready(function() {
			$("#my_form").attr("action",url); 
		});
	</script>

	<script src="{% static 'wordclouds/scripts/username.js' %}"></script>

</body>
</html>